//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _KIWIBUZZER_H_
#define _KIWIBUZZER_H_

#include <TinyCLR_Interop.h>
struct Library_KiwiBuzzer_KiwiBuzzer_Program
{
    static const int FIELD_STATIC___macBase = 0;
    static const int FIELD_STATIC___N = 1;
    static const int FIELD_STATIC___offset = 2;
    static const int FIELD_STATIC__Lcd = 3;
    static const int FIELD_STATIC___nodeSynced = 4;
    static const int FIELD_STATIC___startTime = 5;


    //--//

};

struct Library_KiwiBuzzer_KiwiBuzzer_Resources
{
    static const int FIELD_STATIC__manager = 6;


    //--//

};

struct Library_KiwiBuzzer_KiwiBuzzer_VersionInfo
{
    static const int FIELD_STATIC___theVersion = 7;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_KiwiBuzzer;

#endif  //_KIWIBUZZER_H_
